# Generated by Django 4.0.4 on 2022-04-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(verbose_name='date published')),
                ('Descripcion', models.CharField(max_length=255)),
            ],
        ),
    ]
