# Generated by Django 4.0.4 on 2022-04-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='Fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
